name: Run step in Docker

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: hieupth/tritonserver:24.08
      options: --user root
      volumes:
        - ./models:/models
      env:
        MODEL_PATH: /models
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - uses: actions/checkout@v4
      - run: dir
      - name: prepare
        run: |
          wget https://huggingface.co/datasets/hero-nq1310/stablediffusion-hub/resolve/main/pretrained.zip
          unzip pretrained.zip -d models
      - name: install repo
        working-directory: ${{github.workspace}}
        run: | 
          pip install -r requirements.txt -e .
          bash cnext_convert.sh
      - uses: actions/download-artifact@v4
        with:
          name: my-artifact
      - name: Display structure of downloaded files
        run: ls -R

      
            