name: Run step in Docker

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    container:
      image: hieupth/tritonserver:24.08
      volumes:
        - ./models:/models
      env:
        MODEL_PATH: /models
    steps:
      - name: Check for dockerenv file
        run: (ls /.dockerenv && echo Found dockerenv) || (echo No dockerenv)

      - name: prepare
        run: |
          wget https://huggingface.co/datasets/hero-nq1310/stablediffusion-hub/resolve/main/pretrained.zip
          unzip pretrained.zip -d /models
          pip install -r requirements.txt
          ./sdserve/scripts/optinum_convert_sd.sh
          

      
            