name: Run step in Docker

on: [push]

jobs:
  container-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run step in container
        uses: addnab/docker-run-action@v3
        with:
          image: hieupth/tritonserver:24.08
          volumes:
            - ./models:/models
          run: wget https://huggingface.co/datasets/hero-nq1310/stablediffusion-hub/resolve/main/pretrained.zip
          run: unzip pretrained.zip -d /models
          run: pip install -r requirements.txt
          run: bash -c "./sdserve/scripts/optinum_convert_sd.sh"
          

      
            